blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from blog.views import Index, DetailPost

app_name = 'blog'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('<slug:post_slug>/', DetailPost.as_view(), name='post'),
]

# Serve files locally if not in prod
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

psite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('markdownx/', include('markdownx.urls')),
    path('tracking/', include('tracking.urls')),
    path('', include('blog.urls')),  # Root
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify

from markdownx.models import MarkdownxField


def get_upload_path(instance, filename):
    """ Find the upload path of the background_image dynamically."""
    return "%s/%s" % (instance.slug, 'bg_image.png')


class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(is_draft=False, published_date__lte=timezone.now())


class Post(models.Model):
    # Data definition
    title = models.TextField()
    description = models.TextField()
    content = MarkdownxField()
    is_draft = models.BooleanField(default=False) # Either Draft or Published
    published_date = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=255, blank=True)
    background_image = models.ImageField(upload_to=get_upload_path)

    # PostQuerySet becomes the manager
    objects = PostQuerySet.as_manager()

    class Meta:
        ordering = ('-published_date',)

    def __str__(self):
        return self.title

    # TODO: fix this mess
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            
        super(Post, self).save(*args, **kwargs)

    def make_published(self):
        """ Turns an unpublished Post into a published one.
        If the Post is already published, do nothing.
        """
        self.published_date = timezone.now()
        self.is_draft = False
        self.save()

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView
from blog.models import Post
from django.db import models
from django.urls import reverse
from django.core.cache import cache

from .markdown_wrap import markdown

# TODO: There's something terribly wrong here... but how to place it in the right place?
def limit_to_published(request) -> models.QuerySet:
    posts = Post.objects.all()
    # If not a superuser...
    if not request.user.is_superuser:
        posts = posts.published()  # limit our query to only published objects

    return posts


class Index(ListView):
    model = Post
    template_name = 'blog/index.html'

    def get(self, request, *args, **kwargs):
        posts = limit_to_published(request)
        context = {'post_list': posts}
        return render(request, self.template_name, context)

class DetailPost(DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get(self, request, *args, **kwargs):
        post_list = limit_to_published(request)
        post_slug = self.kwargs['post_slug']
        cache_key = reverse('blog:post', args=[post_slug]) # use our cache key as the URL
        cache_time = 86400
        post = cache.get(cache_key) # if the pots doens't exist, return None

        if True:
            post = get_object_or_404(post_list, slug=post_slug)
            # Use our markdown wrapper defined in markdown_wrap.py
            post.content = markdown(post.content)  # Make the post rendered
            cache.set(cache_key, post, cache_time)

        context = {'post': post}
        return render(request, 'blog/show_post.html', context)

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>
			xy2_ : blog
    </title>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'blog/tachyons.min.css' %}">
    <style>
    body {
    background:
      /* On "top" */
      repeating-linear-gradient(
        45deg,
        transparent,
        transparent 1.5%,
        #2e53b0 1.5%,
        #2e53b0 2.8%
      ),
      /* on "bottom" */
      linear-gradient(
        to bottom,
        #fff,
        #dadeda
      );
    }
    </style>
  </head>
  <body class="sans-serif">
    <div class="bg-white min-vh-100 shadow-3 w-90-ns pl3-ns pv3 mt2 mt0-ns flex-ns flex-none">
      <header class="w-30-ns ph3">
        <h2 class="f2 lh-title fw9 mt0 mr3 mb0 dib">
          xy2_
        </h2>
        <a class="link black hover-silver dib h2 w2 mr3" href="https://github.com/xy2iii" title="GitHub">
          <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M8 0C3.58 0 0 3.582 0 8c0 3.535 2.292 6.533 5.47 7.59.4.075.547-.172.547-.385 0-.19-.007-.693-.01-1.36-2.226.483-2.695-1.073-2.695-1.073-.364-.924-.89-1.17-.89-1.17-.725-.496.056-.486.056-.486.803.056 1.225.824 1.225.824.714 1.223 1.873.87 2.33.665.072-.517.278-.87.507-1.07-1.777-.2-3.644-.888-3.644-3.953 0-.873.31-1.587.823-2.147-.083-.202-.358-1.015.077-2.117 0 0 .672-.215 2.2.82.638-.178 1.323-.266 2.003-.27.68.004 1.364.092 2.003.27 1.527-1.035 2.198-.82 2.198-.82.437 1.102.163 1.915.08 2.117.513.56.823 1.274.823 2.147 0 3.073-1.87 3.75-3.653 3.947.287.246.543.735.543 1.48 0 1.07-.01 1.933-.01 2.195 0 .215.144.463.55.385C13.71 14.53 16 11.534 16 8c0-4.418-3.582-8-8-8"/></svg>
        </a>
        <a class="link black hover-silver dib h2 w2 mr3" href="https://fr.linkedin.com/in/hugo-elhaj-lahsen-80a147164" title="LinkedIn">
          <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M13.632 13.635h-2.37V9.922c0-.886-.018-2.025-1.234-2.025-1.235 0-1.424.964-1.424 1.96v3.778h-2.37V6H8.51V7.04h.03c.318-.6 1.092-1.233 2.247-1.233 2.4 0 2.845 1.58 2.845 3.637v4.188zM3.558 4.955c-.762 0-1.376-.617-1.376-1.377 0-.758.614-1.375 1.376-1.375.76 0 1.376.617 1.376 1.375 0 .76-.617 1.377-1.376 1.377zm1.188 8.68H2.37V6h2.376v7.635zM14.816 0H1.18C.528 0 0 .516 0 1.153v13.694C0 15.484.528 16 1.18 16h13.635c.652 0 1.185-.516 1.185-1.153V1.153C16 .516 15.467 0 14.815 0z" fill-rule="nonzero"/></svg>
        </a>
        <h2 class="f6 mid-gray mb2">
          My thoughts on programming and other stuff
        </h2>
      </header>
      <div class="w-70-ns mh3-ns">
        <section class="mw7 center">
          <h2 class="f4 f2-ns ph3 ph0-ns pt2 pt0-ns bt b--dashed b--black-10 bl-0 br-0 bb-0 bn-ns mb2 mb1-ns mt0">Posts</h2>
	        {% for post in post_list %}
          <article class="pv2 bt b--dark-blue ph3 ph2-l">
            <a href="{% url 'blog:post' post.slug %}" class="f4 f3-ns avenir mt0 lh-title di dim no-underline">{{ post.title }}</a>
            <time class="pl3 gray di">{{ post.published_date|date:"M d, Y"}}</time>
            <p class="f6 f5-ns lh-copy mb0 mt1">
                {{ post.description }}
            </p>
          </article>
	        {% endfor %}
        </section>
      </div>
    </div>
  </body>
</html>

blog/templates/blog/show_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>
			{{ post.title }} : xy2_
    </title>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'blog/tachyons.min.css' %}">
  </head>
  <body class="sans-serif">
    <div class="cover bg-left bg-center-l" style="background-image: url({{ post.background_image.url }})">
      <header class="bg-black-30 cover" >
        <div class="ph3 pt2 pb2 ph4-ns pt5-ns pb5-ns ph6-l">
          <h1 class="f-subheadline-ns f2 measure lh-title white">{{ post.title }}</h1>
        </div>
      </header>
    </div>

    <article class="flex-ns flex-none justify-between">
    <header class="w5-ns">
      <div class="pl3 pt3 mr3-ns lh-copy pb1 b--black-40 bb">
        <p class="f6 mt0 mr1 mb0 dib tracked gray">
	        xy2_</p>
	      <time class="f6 mt0 mr3 mb0 dib gray">
          : {{ post.published_date|date:"M d, Y"}}
        </time>
        <div class="dib">
          <a class="link gray hover-silver dib h1 w1 mr3" href="https://github.com/xy2iii" title="GitHub">
            <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M8 0C3.58 0 0 3.582 0 8c0 3.535 2.292 6.533 5.47 7.59.4.075.547-.172.547-.385 0-.19-.007-.693-.01-1.36-2.226.483-2.695-1.073-2.695-1.073-.364-.924-.89-1.17-.89-1.17-.725-.496.056-.486.056-.486.803.056 1.225.824 1.225.824.714 1.223 1.873.87 2.33.665.072-.517.278-.87.507-1.07-1.777-.2-3.644-.888-3.644-3.953 0-.873.31-1.587.823-2.147-.083-.202-.358-1.015.077-2.117 0 0 .672-.215 2.2.82.638-.178 1.323-.266 2.003-.27.68.004 1.364.092 2.003.27 1.527-1.035 2.198-.82 2.198-.82.437 1.102.163 1.915.08 2.117.513.56.823 1.274.823 2.147 0 3.073-1.87 3.75-3.653 3.947.287.246.543.735.543 1.48 0 1.07-.01 1.933-.01 2.195 0 .215.144.463.55.385C13.71 14.53 16 11.534 16 8c0-4.418-3.582-8-8-8"/></svg>
          </a>
          <a class="link gray hover-silver dib h1 w1 mr3" href="https://fr.linkedin.com/in/hugo-elhaj-lahsen-80a147164" title="LinkedIn">
            <svg fill="currentColor" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" fill-rule="evenodd" clip-rule="evenodd" stroke-linejoin="round" stroke-miterlimit="1.414"><path d="M13.632 13.635h-2.37V9.922c0-.886-.018-2.025-1.234-2.025-1.235 0-1.424.964-1.424 1.96v3.778h-2.37V6H8.51V7.04h.03c.318-.6 1.092-1.233 2.247-1.233 2.4 0 2.845 1.58 2.845 3.637v4.188zM3.558 4.955c-.762 0-1.376-.617-1.376-1.377 0-.758.614-1.375 1.376-1.375.76 0 1.376.617 1.376 1.375 0 .76-.617 1.377-1.376 1.377zm1.188 8.68H2.37V6h2.376v7.635zM14.816 0H1.18C.528 0 0 .516 0 1.153v13.694C0 15.484.528 16 1.18 16h13.635c.652 0 1.185-.516 1.185-1.153V1.153C16 .516 15.467 0 14.815 0z" fill-rule="nonzero"/></svg>
          </a>
        </div>
        <a href="{% url 'blog:index' %}" class="pl3 f4 no-underline di db-ns dim">Home</a>
      </div>
    </header>
    <div class="content bg-white f5 lh-copy mw7 justify-self-c">
      {{ post.content|safe }}
    </div>
    <div class="w5"></div>
    </article>
  </body>
</html>

templates/markdownx/widget2.html
<div class="markdownx" style="display: flex">
    <div style="margin: 20px 10px 20px 0px">
        {% include 'django/forms/widgets/textarea.html' %}
    </div>
    <div style="margin: 20px 0px 20px 0px; overflow:scroll; height:600px;">
        <div class="markdownx-preview"></div>
    </div>
</div>